Update patch set 2
Patch Set 2: Code-Review+1

> Patch Set 1:
> 
> Can you tell me what device tree and build tree you are using?

bugs:
bootable/recovery/twinstall.cpp:201:67: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'long long' [-Werror,-Wformat]
LOGINFO("has_legacy_properties: mmap (size=%zu) failed: %s!\n", finfo.st_size, strerror(errno));
                                           ~~~                  ^~~~~~~~~~~~~
                                           %lld

This patch is needed to fix this error and it doesn't affect arm64 devices, checked on MIX2S here.

Patch-set: 2
Reviewer: Gerrit User 1002261 <1002261@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=+1