Update patch set 1
Patch Set 1:

> > Fixes compile/build errors in updater/otautil. Note that it still
 > > fails due to a build error in applypatch: https://gist.github.com/lambdadroid/1d80b82e494d673536ecaafb3e1240ad
 > > (not entirely sure what's the best way  to fix it)
 > 
 > try with "../bmlutils/bmlutils.h"
 > 
 > it's fix it

It still fails later due to:

bootable/recovery/applypatch/applypatch.cpp:296: error: undefined reference to 'mtd_scan_partitions'
bootable/recovery/applypatch/applypatch.cpp:300: error: undefined reference to 'mtd_find_partition_by_name'
bootable/recovery/applypatch/applypatch.cpp:306: error: undefined reference to 'mtd_write_partition'
bootable/recovery/applypatch/applypatch.cpp:312: error: undefined reference to 'mtd_write_data'
bootable/recovery/applypatch/applypatch.cpp:319: error: undefined reference to 'mtd_erase_blocks'
bootable/recovery/applypatch/applypatch.cpp:325: error: undefined reference to 'mtd_write_close'
bootable/recovery/applypatch/applypatch.cpp:0: error: undefined reference to 'mtd_write_close'

Patch-set: 1