Update patch set 3
Patch Set 3:

Something in the last 5 bootable merges broke the build: http://paste.omnirom.org/view/aa14bd8d

Two of us got the same twrpTar.cpp:718 error when trying to compile.

Patch-set: 3
Reviewer: Gerrit User 1000133 <1000133@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=0