Change class for orscmd to prevent compile error
Using RECOVERY_EXECUTABLES on x86 targets in Omni 7.1 causes a compile error
related to packing relocations:

ERROR: Missing or empty .rel.dyn or .rela.dyn section
ERROR: Failed to load as ELF

This change fixes the compile error.

Change-Id: I60e637158c324295c42c480139d6d38157ba0d31