Update patch set 9
Patch Set 9: Code-Review-1

Causes build to fail in 5.1 tree.

bootable/recovery/gui/action.cpp: In member function 'int GUIAction::decrypt(std::string)':
bootable/recovery/gui/action.cpp:1504:69: error: 'stoi' was not declared in this scope
    op_status = PartitionManager.Decrypt_Device(Password, stoi(userID));
                                                                     ^
build/core/binary.mk:620: recipe for target '/data/Android/build/omni/android-5.1/out/target/product/m8/obj/STATIC_LIBRARIES/libguitwrp_intermediates/action.o' failed
make: *** [/data/Android/build/omni/android-5.1/out/target/product/m8/obj/STATIC_LIBRARIES/libguitwrp_intermediates/action.o] Error 1

Patch-set: 9
Reviewer: Gerrit User 1000092 <1000092@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=-1