gpt: Add -Wno-format-security
The existing -Wno-format requires it:

error: -Wformat-security ignored without -Wformat [-Werror=format-security]

Change-Id: I9e4177df3437f582b7c71fdaf364ab3b7ced595e
Signed-off-by: D. Andrei Măceș <andrei@unlegacy-android.org>