Update patch set 1
Patch Set 1:

> Can you tell us what compile error you are seeing? Should the
 > previous instance of the variable be casted.

The problem only exists on arm32 target, the error is showing that it expects long long similar to this
error: format specifies type 'long long' but the argument has type 'long'

Patch-set: 1