Update patch set 2
Patch Set 2: Code-Review+1

bugs:
bootable/recovery/dosfstools/src/check.c:591:4: error: format specifies type 'unsigned long' but the argument has type 'unsigned long long' [-Werror,-Wformat]
(uint64_t)clusters * fs->cluster_size,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

This patch is needed to fix this error and it doesn't affect arm64 devices, checked on different devices here.

Patch-set: 2
Reviewer: Gerrit User 1002261 <1002261@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=+1